/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cycloplex;

import cycloplex.CyclomaticComplexity;

public class App {
    public String getGreeting() {
        return "Hello World! ;)";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        CyclomaticComplexity comp = new CyclomaticComplexity();
        // comp.checkFile("teste.java");
        comp.checkFilesDir("/home/icaro/Documentos/johan");
    }
}
